version: '3'

services:

  app:
    image: spring-banking-api:latest
    build:
      context: .
    container_name: app
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3307/banking
      - SPRING_DATASOURCE_USERNAME=springuser
      - SPRING_DATASOURCE_PASSWORD=ThePassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    depends_on:
      - docker-mysql
    networks:
      - banking

  docker-mysql:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=banking
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
    ports:
      - 3307:3306
    networks:
      - banking

networks:
  banking:
    external:
      name: banking