version: '3'

services:

  app:
    image: static254/spring-banking-api:1.0.0
#    build:
#      context: .
    container_name: app
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/banking
      - SPRING_DATASOURCE_USERNAME=springuser
      - SPRING_DATASOURCE_PASSWORD=ThePassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    links:
      - db
    restart: on-failure
    networks:
      - banking

  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=banking
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_ROOT_HOST=%
    ports:
      - 3307:3306
    networks:
      - banking

networks:
  banking:
    external:
      name: banking